<a href="https://colab.research.google.com/github/shivammishra000/NLP-Natural-Language-Processing/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install NLTK

## NLTK
Natural langauage tookkit - python library use for tokenization, stemming, lemmatization, etc. one of the oldest and most widely used libraries for classical NLP

In [ ]:
import nltk

In [ ]:
sentence = """At eight o'clock on Thursday morning... Arthur didn't feel very good."""

In [ ]:
from nltk.tokenize import sent_tokenize

In [ ]:
documents = sent_tokenize(sentence)

In [ ]:
print(documents)

["At eight o'clock on Thursday morning... Arthur didn't feel very good."]


In [ ]:
from nltk import word_tokenize

In [ ]:
word_tokenize(sentence)

['At',
 'eight',
 "o'clock",
 'on',
 'Thursday',
 'morning',
 '...',
 'Arthur',
 'did',
 "n't",
 'feel',
 'very',
 'good',
 '.']

In [ ]:
from nltk.tokenize import wordpunct_tokenize

In [ ]:
wordpunct_tokenize(sentence)

['At',
 'eight',
 'o',
 "'",
 'clock',
 'on',
 'Thursday',
 'morning',
 '...',
 'Arthur',
 'didn',
 "'",
 't',
 'feel',
 'very',
 'good',
 '.']

In [ ]:
from nltk.tokenize import TreebankWordDetokenizer

In [ ]:
tokenizer = TreebankWordDetokenizer()

In [ ]:
tokenizer.tokenize(sentence)

"A t   e i g h t   o' c l o c k   o n   T h u r s d a y   m o r n i n g . . .   A r t h u r   d i d n' t   f e e l   v e r y   g o o d."

In [ ]:
# Stemming

In [ ]:
# Classification problem
# Positive or Negative
# Reviews -> eating, eat, eaten [going, gone, goes]

In [ ]:
words = [
    "play", "playing", "played", "plays",
    "studies", "easily", "happiness", "flies", "crying", "university",
    "cats", "boxes", "parties",
    "national", "nationality", "nationalize",
    "connect", "connected", "connecting", "connection", "connections",
    "better", "went", "mice"
]

In [ ]:
## PorterStemmer

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
stemming = PorterStemmer()

In [ ]:
for word in words:
    print(stemming.stem(word))

play
play
play
play
studi
easili
happi
fli
cri
univers
cat
box
parti
nation
nation
nation
connect
connect
connect
connect
connect
better
went
mice


In [ ]:
from nltk.stem import RegexpStemmer

In [ ]:
reg_stemmer = RegexpStemmer('ing$|s$|ed$|able$', min=4)

In [ ]:
for word in words:
  print(reg_stemmer.stem(word))

play
play
play
play
studie
easily
happines
flie
cry
university
cat
boxe
partie
national
nationality
nationalize
connect
connect
connect
connection
connection
better
went
mice


In [ ]:
from nltk.stem import SnowballStemmer

In [ ]:
snow_stemmer = SnowballStemmer(language='english')

In [ ]:
for word in words:
  print(snow_stemmer.stem(word))

play
play
play
play
studi
easili
happi
fli
cri
univers
cat
box
parti
nation
nation
nation
connect
connect
connect
connect
connect
better
went
mice


In [ ]:
## Lemmatization

In [ ]:
# Wordnet Lammatizer

In [1]:
import nltk
nltk.download('wordnet') # wordnet -> database of english
nltk.download('omw-1.4') # open multilingual wordnet, verson 1.4
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


In [2]:
lemmatizer = WordNetLemmatizer()

In [3]:
words = ["studies", "running", "better", "went", "files", "mice"]

In [4]:
for word in words:
  print(lemmatizer.lemmatize(word))

study
running
better
went
file
mouse


In [8]:
print(lemmatizer.lemmatize("running", pos='v')) # v-> verb, pos -> part of speech
print(lemmatizer.lemmatize("better", pos='a')) # a-> adjective
print(lemmatizer.lemmatize("went", pos='v')) # n-> verb

run
good
go


In [16]:
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt_tab')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [17]:
from nltk import pos_tag, word_tokenize

In [18]:
sentence = "The dog runs quickly"
tokens = word_tokenize(sentence)
print(pos_tag(tokens))

[('The', 'DT'), ('dog', 'NN'), ('runs', 'VBZ'), ('quickly', 'RB')]


In [19]:
## stopword removal

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [22]:
from nltk.corpus import stopwords

In [23]:
stop_words = set(stopwords.words('english'))

In [24]:
print(stop_words)

{'their', 'is', "needn't", 'him', "he'd", 'have', 'herself', 'when', 'against', 'on', 'being', 'out', 'an', 'm', 'now', "they'd", 'do', 'itself', "you've", 'couldn', 'for', 'am', 'her', 'same', 'because', "we'll", "you'd", "he's", 'just', 'after', 'mightn', 'were', 'most', 'not', "i'm", "mustn't", 'between', "won't", 'hers', 'isn', 'its', 'both', 'theirs', "they've", 'has', 'won', 'should', "we're", 'you', 'off', 'shouldn', 'only', 'other', "mightn't", 'those', 'there', "it's", 'at', 'all', "weren't", 've', 'having', 'hasn', 'he', "they'll", 'these', 'further', 'needn', 'been', 'this', 'up', 'ma', 'some', "shouldn't", 'or', 'until', 'ours', "i'll", 're', 'she', 'himself', "i'd", "should've", 'weren', 'shan', 'from', "she'd", 'o', 'them', "wasn't", 'but', 'are', 'nor', 'where', 'can', 'while', 'so', 'y', 'mustn', 'into', 'does', "he'll", "don't", 'themselves', 'very', 'no', "aren't", 'whom', 'such', 'they', 'me', "doesn't", 't', "you'll", 'by', 'before', 'ourselves', 'myself', 'was', 'h

In [25]:
sentence2 = "This is a simple example showing how to remove stop words from a sentence"
tokens = word_tokenize(sentence2)

In [26]:
filtered_tokens = [word for word in tokens if word.lower() not in stop_words]

In [27]:
print("Orignial:", tokens)
print("Filtered:", filtered_tokens)

Orignial: ['This', 'is', 'a', 'simple', 'example', 'showing', 'how', 'to', 'remove', 'stop', 'words', 'from', 'a', 'sentence']
Filtered: ['simple', 'example', 'showing', 'remove', 'stop', 'words', 'sentence']


In [35]:
from nltk.corpus import wordnet

In [40]:
## tokenization, postag, lemmatized

text = "The cats were running quickly and playing better than before"

# Tokenize
tokens = word_tokenize(text)
print("Tokens", tokens)

Tokens ['The', 'cats', 'were', 'running', 'quickly', 'and', 'playing', 'better', 'than', 'before']


In [41]:
# pos_tag
tags = pos_tag(tokens)
print("POS Tagging", tags)

POS Tagging [('The', 'DT'), ('cats', 'NNS'), ('were', 'VBD'), ('running', 'VBG'), ('quickly', 'RB'), ('and', 'CC'), ('playing', 'VBG'), ('better', 'JJR'), ('than', 'IN'), ('before', 'IN')]


In [42]:
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [43]:
from nltk.metrics.paice import get_words_from_dictionary
# lemmatize using pos
lemmatized = [lemmatizer.lemmatize(w, pos=get_wordnet_pos(t)) for w, t in tags]
print("Lemmatized", lemmatized)

Lemmatized ['The', 'cat', 'be', 'run', 'quickly', 'and', 'play', 'good', 'than', 'before']


In [44]:
# Remove stop words
final_tokens = [word for word in lemmatized if word.lower() not in stop_words]
print(final_tokens)

['cat', 'run', 'quickly', 'play', 'good']


## Bag-of-words(Bow) -> counts numbers of words and convert it into vectors

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

In [47]:
documents = [
    "the cat sat on the mat",
    "the dog sat on the log",
    "cats and dogs are friends"
]

vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(bow_matrix.toarray())

['and' 'are' 'cat' 'cats' 'dog' 'dogs' 'friends' 'log' 'mat' 'on' 'sat'
 'the']
[[0 0 1 0 0 0 0 0 1 1 1 2]
 [0 0 0 0 1 0 0 1 0 1 1 2]
 [1 1 0 1 0 1 1 0 0 0 0 0]]


In [49]:
import numpy as np

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

for word, idx in vectorizer.vocabulary_.items():
  print(f"{word:10} IDF = {vectorizer.idf_[idx]:.4f}")

print()
print("TF-IDF matrix (normalized):")
print(np.round(tfidf_matrix.toarray(), 2))

the        IDF = 1.2877
cat        IDF = 1.6931
sat        IDF = 1.2877
on         IDF = 1.2877
mat        IDF = 1.6931
dog        IDF = 1.6931
log        IDF = 1.6931
cats       IDF = 1.6931
and        IDF = 1.6931
dogs       IDF = 1.6931
are        IDF = 1.6931
friends    IDF = 1.6931

TF-IDF matrix (normalized):
[[0.   0.   0.43 0.   0.   0.   0.   0.   0.43 0.33 0.33 0.65]
 [0.   0.   0.   0.   0.43 0.   0.   0.43 0.   0.33 0.33 0.65]
 [0.45 0.45 0.   0.45 0.   0.45 0.45 0.   0.   0.   0.   0.  ]]


## sentiment classifier

In [5]:
import nltk
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


True

In [6]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag

In [7]:
texts = [
    "I love this movie, it was amazing",
    "This film was fantastic and inspiring",
    "Best movie I have ever seen",
    "What a wonderful and heartwarming story",
    "I really enjoyed watching this",
    "This movie was terrible and boring",
    "Worst film I have ever seen",
    "I hated every moment of this",
    "This was a complete waste of time",
    "Absolutely awful and disappointing movie"
]

labels = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]

In [8]:
# preprocess pipeline

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def get_wordnet_pos(tag):
  if tag.startswith('J'):
    return wordnet.ADJ
  elif tag.startswith('V'):
    return wordnet.VERB
  elif tag.startswith('N'):
    return wordnet.NOUN
  elif tag.startswith('R'):
    return wordnet.ADV
  else:
    return wordnet.NOUN

def preprocess(text):
  tokens = word_tokenize(text)
  tags = pos_tag(tokens)
  lemmatized = [lemmatizer.lemmatize(w, pos=get_wordnet_pos(t)) for w, t in tags]
  clean = [w.lower() for w in lemmatized if w.lower() not in stop_words and w.isalpha()]
  return " ".join(clean)

cleaned_texts = [preprocess(t) for t in texts]

for original, cleaned in zip(texts, cleaned_texts):
  print(f"{original:45} -> {cleaned}")

I love this movie, it was amazing             -> love movie amaze
This film was fantastic and inspiring         -> film fantastic inspire
Best movie I have ever seen                   -> best movie ever see
What a wonderful and heartwarming story       -> wonderful heartwarming story
I really enjoyed watching this                -> really enjoy watch
This movie was terrible and boring            -> movie terrible boring
Worst film I have ever seen                   -> worst film ever see
I hated every moment of this                  -> hat every moment
This was a complete waste of time             -> complete waste time
Absolutely awful and disappointing movie      -> absolutely awful disappointing movie


In [9]:
## convert TF_IDF vector

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(cleaned_texts)

print(X.shape)

(10, 27)


In [11]:
## Train a classifier

In [13]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, labels, test_size=0.3, random_state=42)

model = MultinomialNB()
model.fit(X_train, Y_train)

accuracy = model.score(X_test, Y_test)
print(f"Accuracy: {accuracy}")

Accuracy: 0.3333333333333333


In [15]:
new_sentences = [
    "This was an incredible and beautiful film",
    "I did not enjoy this movie at all"
]

cleaned_new  = [preprocess(s) for s in new_sentences]
new_vectors = vectorizer.transform(cleaned_new)

predictions = model.predict(new_vectors)

for sentence, pred in zip(new_sentences, predictions):
  sentiment = "positive" if pred == 1 else "Negative"
  print(f"{sentence:45} -> {sentiment}")

This was an incredible and beautiful film     -> Negative
I did not enjoy this movie at all             -> positive


In [19]:
print("Shivam mishra rejected by the company")

Shivam mishra rejected by the company
